### ISSUE TITLE
Conflict with Stock ProjectE

### ISSUE THREAD

**Issue by CindyLouWho03** [LatvianModder/Project-EX#2]
The Tome Of Knowledge is already craftable in stock ProjectE assumbing you change the config to make it craftable. Using your mod adds 2 recipes for the tome, one being easy but the other being your stupidly hard one

(keep note i havent tested, but im assumbing this wasnt caught)

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/Project-EX/issues/3
