### ISSUE TITLE
No EMC generating

### ISSUE THREAD

**Issue by mac2040** [LatvianModder/Project-EX#25]
in ProjectEX-1.1.0.17 the personal emc  link and all the collector do not generate any emc downgrade to ProjectEX-1.1.0.16 version to get it to work again

**Comment by cf-Botan** [comment]
Persists in ProjectEX-1.1.0.18 but only in single player mode. EMC Generation in MP works fine.

**Comment by STFUMeelteeth** [comment]
Version bug? (i'm russian, and translator translator does not translate to the end)
