### ISSUE TITLE
Can't find option to make the final star give infinite EMC, either it's not there, or I can't find it.

### ISSUE THREAD

**Issue by SAKO4444GODZ** [LatvianModder/Project-EX#27]
[projectex.txt](https://github.com/LatvianModder/Project-EX/files/3006447/projectex.txt)
Attached is my config file.
Project EX is version 1.1.0.19
Project E is version 1.4.0
Forge is 14.23.5.2796
Windows 10

**Comment by Konngitas** [comment]
I looked in the game files, and found the description of the item, which does not show up in game for some reason. You are meant to put the final star in a Dark Matter Pedestal, activate the pedestal, then put a chest next to it. then you throw an item(whether it needs to have emc or not is in the config), and it will duplicate one stack of that item around every second or so, into that chest. then you can just pipe those items in to a link for pretty much infinite emc gen, more than you'll ever use anyway.

**Comment by SAKO4444GODZ** [comment]
Sorry for the necro, but I just found this again, yes this solves the issue.
