### ISSUE TITLE
Crash: Personal EMC link issue or mod conflict?

### ISSUE THREAD

**Issue by Screw4ff** [LatvianModder/Project-EX#31]
Here's what's going on, every time I load up my world, everything is perfectly fine, until, I get too close to my personal EMC link, then the game crashes and this is the error I receive
Error: java.lang.NoClassDefFoundError: moze_intel/projecte/api/event/PlayerAttemptCondenserSetEvent

any fix or suggestions are appreciated, here is the crash report:
[crash-2019-04-03_20.36.53-client.txt](https://github.com/LatvianModder/Project-EX/files/3041491/crash-2019-04-03_20.36.53-client.txt)

EDIT: Should point out, the crash only seems to occur when looking at the link, however,  WaIla and Hwyla dont seem responsible for the crash since it still occurs without them.

E2: Upon loading the world without projectEx, loading the chunk that used to have the emc link in it, along with other PEX blocks, then reloading with PEX installed, some blocks reappear, making the Link difficult to remove. 

E3: The same Issue occurs with the the refined link.

**Comment by LatvianModder** [comment]
Seems like you have outdated Project E version. Make sure you have updated both mods
