### ISSUE TITLE
Mod interaction crash (AE2)

### ISSUE THREAD

**Issue by demethan** [LatvianModder/Project-EX#32]
Hi, 
I am playing Sky Odyssey. I put a storage bus from Applied Energistic on a refined EMC link for easy resource. Works fine in the crafting terminal and I can craft whatever I want. If I start autocrafting, the server freezes then gets shutdown by watchdog. I tried to product a crashlog, no go!. 

I will be linking this issue in the AE2 issue tracker.  Not sure where is the problem.

**Comment by demethan** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3994

**Comment by jarquafelmu** [comment]
I have added more information to your issue on the AE2 github. I am also going to reference both of these issues on the ProjectE github as they might need to be involved with resolving this.
