### ISSUE TITLE
Crashing/Infinite Load World caused by ItemColossalStar abstract method

### ISSUE THREAD

**Issue by salaandora** [LatvianModder/Project-EX#42]
Hello!

Project EX seems to be causing my game to crash on the "load world" screen, preventing the world from loading and causing an infinite load world time.

I am not very savvy with java, nor with github, so I have uploaded the crash report text file here, rather than attempting a fix myself.

The error message is:
EDT
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ProjectE (projecte)
Caused by: java.lang.AbstractMethodError: Method com/latmod/mods/projectex/item/ItemColossalStar.getStoredEmc(Lnet/minecraft/item/ItemStack;)J is abstract

Of course,more information is in the text file.

Thank you and please let me know what else I can provide to help resolve the issue.

NOTE: I have attempted this using three different editions of the mod: the newest, and two slightly older ones, so mod version does not seem to be the main issue.

[crash-2019-05-04_01.50.09-server.txt](https://github.com/LatvianModder/Project-EX/files/3144660/crash-2019-05-04_01.50.09-server.txt)

**Comment by LatvianModder** [comment]
You need to update Project E

**Comment by salaandora** [comment]
Thanks for the reply! I am currently using the latest version of Project E (ProjectE-1.12.2-PE1.4.1.jar)

**Comment by LatvianModder** [comment]
I see, you aren't on latest PEX version

**Comment by frenzye** [comment]
https://gist.github.com/frenzye/d078f04ae0af31b393381dbb2d0391fd
