### ISSUE TITLE
emc values wrap wrap around at ~8E with version 35. 

### ISSUE THREAD

**Issue by jmbjorndalen** [LatvianModder/Project-EX#43]
I tried ProjectE 1.4.1 and ProjectEX v. 35. The EMC value wraps around at (I think) about 8E and goes negative to about -8E before counting up again. 

Downgrading to 1.4.0  / v. 34 fixes the issue.

**Comment by delta2k** [comment]
im having same problem. mine is counting down. instead of up andfor me downgrading doesn't fix anything. still counting down.

**Comment by LatvianModder** [comment]
Project E bug, report to them
