### ISSUE TITLE
Bug with arcane transmutation tablet

### ISSUE THREAD

**Issue by Testo0987** [LatvianModder/Project-EX#47]
Hello, so i noticed that when i tried to use JEI to auto-fill in the recipe, it would fill in the things from my inventory, instead of the EMC database. Here is the video:
https://youtu.be/7-Z9DMmmXTQ

**Comment by LatvianModder** [comment]
What version of PEX? because this was fixed already

**Comment by Testo0987** [comment]
I'm not sure, but it was fixed now when i updated.
