### ISSUE TITLE
EMC Overflow

### ISSUE THREAD

**Issue by venrob** [LatvianModder/Project-EX#50]
So uh, I made a lot of EMC gen. And it overflowed easily. I now open my tablet to find myself at -2^64 EMC. Given, it generates back to positive without much issue, because.... well, a LOT of EMC gen.

EMC links / power flowers should have a safeguard to make them stop generating if they would cause overflow.

**Comment by Firesparq** [comment]
In my experience, what you are experiencing should only occur when you have stupid amounts of emc generation. The EMC in your tablet caps out at some ridiculous amount, so I'm assuming the reason you're seeing said error is that your generation per tick exceeds this upper limit. Would this be the case?

**Comment by venrob** [comment]
> In my experience, what you are experiencing should only occur when you have stupid amounts of emc generation. The EMC in your tablet caps out at some ridiculous amount, so I'm assuming the reason you're seeing said error is that your generation per tick exceeds this upper limit. Would this be the case?

It caps at MAX_LONG, which should be 2^63-1. In normal ProjectE, this limit is no issue, as it would take something completely stupid that could never be expected to generate enough to overflow that.
...With ProjectEX, and `Final Collectors`, I was able to make a build in a small room which fills that amount in about 3-4 minutes. It took about no effort to build, and could very reasonably be done by anyone using the mod. It shouldn't be too hard to say "If this will put you over the limit, don't do it".
i.e.
`if(MAX_LONG - curEMC > emcPerTick) //Don't generate` or somesuch.

**Comment by Firesparq** [comment]
Ah, I don't think you've understood my assumption. That security guard is already in place (I know for certain it worked in project ozone 3).

That said, what I was suggesting is perhaps of your EMC/t is greater than a max_long, then it generates for 1 tick, and then detects an over the limit error this resulting in your circumstance. Then again, I could be wrong, I was just suggesting a possible reason as to why it is doing what it is for you.

**Comment by venrob** [comment]
Ah, no, it takes 2-3 minutes to go from 0 to MAX_LONG. It simply overflows when it reaches MAX_LONG.

**Comment by LatvianModder** [comment]
This is a Project E bug that has been reported already in here https://github.com/sinkillerj/ProjectE/issues/1887. I will see if I can somehow fix it on my end too.

**Comment by jusitnboggs** [comment]
So this is happening to me too I'm using 
ProjectEX-1.2.0.36.jar	
ProjectE-1.12.2-PE1.4.1.jar

Is there a way to reset my emc to 0 so I can use my tablet again?

**Comment by dedphrog** [comment]
This is happening to me as well.

ProjectEX-1.2.0.36.jar
ProjectE-1.12.2-PE1.4.1.jar

In one gaming session i went from having around 150 MK5 bonsai flowers, to replacing them with 150 mk15 flowers, to replacing them with 150 final flowers.

Now my EMC value is in the negative 50% of my server time, making it impossible to craft from EMC tablet during those long windows.
I went through the configs of ProjectE and ProjectEX and saw nothing yet to cap the value before it rolls over. This seems like a simple thing, could you please add it?

Thanks!
