### ISSUE TITLE
Names of High EMC

### ISSUE THREAD

**Issue by HeelixDash** [LatvianModder/Project-EX#51]
The labeling of high emc items is weird.
The way it should be is (M)illion, (B)illion, (T)rillion, (q)uadrillion, (Q)uintillion
In game, it seems to go (M)illion, (G), (T)rillion, (?), (P)
I'm not sure if this is intentional and I'm missing something or if it was just looked over.

**Comment by jusitnboggs** [comment]
I was too wondering about this.

**Comment by jusitnboggs** [comment]
https://en.wikipedia.org/wiki/Names_of_large_numbers

**Comment by LatvianModder** [comment]
I go by scientific number names. As you can see it quickly becomes a problem when it hits larger scales Quadrillion (Q) and Quintillion (Q again!) and Sextillion and Septillion are also both S. I use this https://en.wikipedia.org/wiki/Metric_prefix

**Comment by jusitnboggs** [comment]
'K', 'M', 'B', 'T', 'Qa', 'Qi', 'Sx', 'Sp', 'Oc', 'No', 'Dc', 'Ud',
'Dd', 'Td', 'Qad', 'Qid', 'Sxd', 'Spd', 'Od', 'Nd', 'V', 'Uv', 'Dv',
'Tv', 'Qav', 'Qiv', 'Sxv', 'Spv', 'Ov', 'Nv', 'Tt'

**Comment by jusitnboggs** [comment]
But I see why you would use Metric Prefix lol atleast you are not doing what I see in phone games M B T AA AB AC lol
