### ISSUE TITLE
Request for event/config for Personal Link

### ISSUE THREAD

**Issue by pupnewfster** [LatvianModder/Project-EX#6]
I would like to request one of two things.

1. A config option to disable the output box for the Personal Link.
2. An event similar to the [PlayerAttemptCondenserSetEvent](https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/api/event/PlayerAttemptCondenserSetEvent.java) I use that event, and the other one I added in the same pull to ProjectE so that I can stage transmutation using CompatSkills. Currently using the output slot lets people bypass the locks on being unable to learn/create new items using EMC. So I would rather just have to add a bit more code to CompatSkills than disable the Personal Link in my pack.

**Comment by LatvianModder** [comment]
I think I will just use this event, since Link is basically condenser MK3

**Comment by pupnewfster** [comment]
Works properly, thanks
