### ISSUE TITLE
Suggestion for your transmutation m2

### ISSUE THREAD

**Issue by Thunder-Nova** [LatvianModder/Project-EX#7]
Been trying to look for what your plans are for the transmutation table m2. Though don't seem to find them. My guess would be that it will auto learn crafting results for materials it's learned. (Such as learning sticks and coal will auto learn torch). If not then it's one suggestion.

And maybe configurable to disable the above function and have a Crafting 3x3 square inside the Transmutation function. (Which I believe should be an easier function to make then what I said above).

Though the main suggestion is for the original table has a tablet. How about that for the M2 you add a gui to player inventory instead of a tablet. This can be done with the M2 crafted into a book that player can "learn".

Pretty much OP in my opinion. Though Project E itself is OP as is. Still love it.

Anyhow this should be crafted using the M2 and last star to create the Transmutation Book. This makes that even in death player still has the Transmutation skill with them and frees up an inventory space. To open this a transmutation icon should appear in at least 10 configurable spot in the player invemtory(due to other mods): 4 corners of the avatar screen. Straight above, bellow, left, or right of the 2x2 crafting spot, or above the left or right of the main inventory. Reason behind this is due to limited keyboard functions due to large modpacks (been in that situation often). Still can add a keyboard function. Though no key set by default.

**EDIT:** You could make use of the Project Tab on this website. Can easily copy paste the suggestions or/and make your own personal edits. Do wish to see your plans for the Transmutation Table M2. This way you can clear the issue page. And make your own personal checklist.

**Comment by LatvianModder** [comment]
You did guess some things, but the plans for MK2 are Crafting Table inside and favorite Item slots around. Transmutation table in inventory could be another tier instead

**Comment by Thunder-Nova** [comment]
Ok great.

These guess and suggestion does fit this add-on more then the project e mod due to how OP it already is. So I am happy to contribute.

**Comment by Vercalos** [comment]
I have to say, I look forward to seeing the Transmutation Table Mk2 being implemented.  The "Crafting Table" functionality alone is something I wanted more than anything else to be added to Project E.

The closest equivalent at the moment seems to be using EMC autocrafting with Equivalent Energistics and Applied Energistics, and even then, that's hardly even close to being the same.
